services:
  web:
    build: .
    container_name: vpn_dashboard_web
    entrypoint: [ "/bin/bash", "/app/scripts/entrypoint.sh" ]
    volumes:
      - .:/app
    ports:
      - "800:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=vpn_dashboard.settings
      - ALLOWED_HOSTS=*
    restart: unless-stopped

  scheduler:
    build: .
    container_name: vpn_dashboard_scheduler
    command: python scheduler.py
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=vpn_dashboard.settings
    restart: unless-stopped
